### ISSUE TITLE
Undeclared global variable

### ISSUE THREAD

**Issue by An0n3m0us** [TumeniNodes/angledwalls#14]
Console log:

`WARNING[Main]: Undeclared global variable "simple" accessed at ...~/.minetest/mods/angledwalls/slopedwalls.lua:17`

**Comment by TumeniNodes** [comment]
not even sure why I added that in. Removed the line, let me know if this resolves the warning, it should

**Comment by An0n3m0us** [comment]
Yep, it's alright now.

**Comment by TumeniNodes** [comment]
Good. I'll push the recent version to ContentDB. Thank you
