### ISSUE TITLE
Need cleaner selection and collision box positions

### ISSUE THREAD

**Issue by TumeniNodes** [TumeniNodes/angledwalls#9]
If anyone knows how to extract geometry for shapes from Blender, so cleaner selection and collision boxes can be used, I would greatly appreciate it, and would also like to learn where to obtain/extract them from.

Thank you in advance

**Comment by An0n3m0us** [comment]
Maybe something like this?:
http://www.nathansalapat.com/blog/creating-collision-boxes-meshes

**Comment by An0n3m0us** [comment]
I don't think that is possible. All Minetest collision and selection boxes are cubes only; they cannot be a mesh FAIK.

**Comment by TumeniNodes** [comment]
I don't think so either. Would be nice if there were some way to use bounding boxes for models from Blender to use as selection boxes in MT

**Comment by An0n3m0us** [comment]
https://github.com/An0n3m0us/Blender2Nodebox

**Comment by TumeniNodes** [comment]
I had looked at that, not sure it will do anything to give a cleaner selection box for my angled doors.
And simply using a 16x32 cube looks horrible.
Maybe, eventually some sort of solution will reveal itself.

**Comment by An0n3m0us** [comment]
Yeah. I think Minetest needs mesh collision boxes instead of just cubic collision boxes.

**Comment by NathanSalapat** [comment]
Okay, so not sure if you want to change the collision boxes, or change the mesh to match your collision boxes. Changing the mesh to match looks like this.
![screenshot_20190906_213525](https://user-images.githubusercontent.com/8930456/64468796-68c44d80-d0ee-11e9-8210-a4c2be3688b0.png)

Also: http://nathansalapat.com/blog/creating-collision-boxes-meshes

**Comment by TumeniNodes** [comment]
> Okay, so not sure if you want to change the collision boxes, or change the mesh to match your collision boxes.

Yes, definitely want the mesh to line up with the selection box.
The sel box I know is straight, as I made it with nbe

I also know I can delete some of those vertical lines of the sel box, (and even all those smaller angles top and bottom) but I'm lazy :P 
I'll get to it eventually

These doors were made similar to the angled glass because using a straight up rectangle model proved to be slightly problematic when rendering, and would have required their own custom textures for UVmapping, and I wanted these able to use the current TP's textures.

But thank you for tackling these crooked doors too Nathan...

**Comment by NathanSalapat** [comment]
Okay. I can get the rest of the models fixed and put in a pull request. Probably will be completed later today,
